image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: ignore

tasks:
  - name: start up buildkitd
    command: sudo /usr/bin/buildkitd --group gitpod --debug
  - name: server a local docker registry
    command: |
      mkdir -p /workspace/registry
      docker run -p 5000:5000 --name registry --rm -v /workspace/registry:/var/lib/registry registry:2 
    openMode: split-right
  - name: get latest version of dazzle, build and test images
    before: |            
      git clone --depth=1 https://github.com/gitpod-io/dazzle/
      cd ./dazzle
      go get -v ./...
      go generate -v ./...
      go install
      go build
      cd ..
    command: |      
      gp await-port 5000
      echo "To build and test chunks 'time sudo $(which dazzle) build localhost:5000/dazzle -v --context dazzle-rewrite-test'"
      echo "To build and test combinations 'time sudo $(which dazzle) combine localhost:5000/dazzle --context dazzle-rewrite-test --all -v'"
      echo "Image content cached in this workspace...'du -shc /workspace/registry/*'"
      
    openMode: tab-after

vscode:
  extensions:
    - ms-azuretools.vscode-docker

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
