version: 2.1

jobs:
  chunks:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            sudo su -c "curl -L -o /usr/bin/runc https://github.com/opencontainers/runc/releases/download/v1.0.0/runc.amd64"
            sudo chmod +x /usr/bin/runc
            curl -L https://github.com/moby/buildkit/releases/download/v0.9.1/buildkit-v0.9.1.linux-amd64.tar.gz | tar xz
            sudo ./bin/buildkitd
          background: true
      - run:
          command: |
            sudo su -c "cd /usr/bin; curl -L https://github.com/gitpod-io/dazzle/releases/download/v0.1.4/dazzle_0.1.4_Linux_x86_64.tar.gz | tar xz"
      - run:
          command: |
            sleep 5
            sh .circleci/dazzle.sh build docker.io/gitpod/workspace-images-dazzle
          no_output_timeout: 20m

  workspace-base:
    docker:
      - image: ghcr.io/gitpod-io/dazzle:v0.1.4
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - attach_workspace:
          at: .
      - run:
          command: |
            sh .circleci/dazzle.sh combine --combination base docker.io/gitpod/workspace-images-dazzle
          no_output_timeout: 30m

  workspace-full:
    docker:
      - image: ghcr.io/gitpod-io/dazzle:v0.1.4
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - attach_workspace:
          at: .
      - run:
          command: |
            sh .circleci/dazzle.sh combine --combination full docker.io/gitpod/workspace-images-dazzle
          no_output_timeout: 30m
          
  workspace-full-vnc:
    docker:
      - image: ghcr.io/gitpod-io/dazzle:v0.1.4
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - attach_workspace:
          at: .
      - run:
          command: |
            sh .circleci/dazzle.sh combine --combination full-vnc --no-test docker.io/gitpod/workspace-images-dazzle
          no_output_timeout: 30m
        
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - chunks
      - workspace-base:
          requires:
            - chunks
      - workspace-full:
          requires:
            - chunks
      - workspace-full-vnc:
          requires:
            - workspace-full
