name: Workspace Images Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dazzle
        uses: actions/checkout@v2
        with:
          repository: gitpod-io/dazzle
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.1
      - run: go get -v ./...
      - run: go generate -v ./…
      - run: go install
      - run: dazzle
