name: Workspace Images Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
      - name: Checkout dazzle
        uses: actions/checkout@v2
        with:
          repository: gitpod-io/dazzle
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.1
      - run: gcloud --help
      - run: go get -v ./...
      - run: go generate -v ./...
      - run: go install
      - run: dazzle # only to ensure dazzle is in the path
      - name: Checkout workspace-images
        uses: actions/checkout@v2
        with:
          repository: gitpod-io/workspace-images
      - run: sudo su -c "cd /usr; curl -L https://github.com/moby/buildkit/releases/download/v0.8.3/buildkit-v0.8.3.linux-amd64.tar.gz | tar xvz"
      - run: sudo buildkitd --group docker &
      - run: sudo chmod +777 /run/buildkit/buildkitd.sock
      - run: docker pull registry:2
      - run: docker run -p 5000:5000 --name registry --rm registry:2 &
      - run: cd dazzle-rewrite && dazzle build localhost:5000/workspace-images
